---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      serviceAccountName: default  # use the SA with IRSA
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: my-app
          image: auwalu5/tshoot:1.0
          ports:
            - containerPort: 80
          volumeMounts:
            - name: secrets-store-inline
              mountPath: /tmp
              readOnly: true
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "supabase-db-secrets"

---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  namespace: default
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "alb" 
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  type: LoadBalancer
  selector:
    app: my-app
  ports:
    - port: 80
      targetPort: 80

